<?php

$code = $_GET['code'];
$api = "https://api.line.me/oauth2/v2.1/token";

//$authen ="grant_type=authorization_code&code=$code;&redirect_uri=https://majestic-biscayne-65338.herokuapp.com/getProfile.php&client_id=1594277893&client_secret=d2a63d13dacf5041464d249127ebf50d";

$body["grant_type"] = "authorization_code";
$body["code"] = $code;
$body["redirect_uri"] = "https://majestic-biscayne-65338.herokuapp.com/getProfile.php";
$body["client_id"] = "1594277893";
$body["client_secret"] = "d2a63d13dacf5041464d249127ebf50d";


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

$ch = curl_init($api); 
curl_setopt($ch, CURLOPT_POST, true); 
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST'); 
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
curl_setopt($ch, CURLOPT_POSTFIELDS, $body); 
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/x-www-form-urlencoded');


$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch); 

//header('Location: http://www.d-sci.co.th/LineQ.html?profile='.$profile_obj->{'displayName'}); 

echo "<br> <br> <br>";

echo $result." <br>";

echo "$code : Test <br> $authen";

//print_r($_GET);


    
